version = 1

exclude_patterns = ["demo_code.py"]

[[analyzers]]
name = "shell"

  [analyzers.meta]
  version = "abc"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "black"

  [transformers.meta]
  version = "123"

[[transformers]]
name = "isort"
